// <auto-generated />
namespace Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mymig6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mymig6));
        
        string IMigrationMetadata.Id
        {
            get { return "202004061446513_mymig6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
