// <auto-generated />
namespace Solution.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class GeoLocations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GeoLocations));
        
        string IMigrationMetadata.Id
        {
            get { return "202004030025090_GeoLocations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
